@startuml
'https://plantuml.com/class-diagram

class ToDoListApp{
    + main()
    + start()
}

class ToDoListController{
    - itemTableView: TableView<Item>
    - isCompletedColumn: TableColumn<Item, CheckBox>
    - descriptionColumn: TableColumn<Item, String>
    - dueDateColumn: TableColumn<Item, LocalDate>

    - descriptionTextField: TextField
    - dueDatePicker: DatePicker
    - itemObservableList: ObservableList<Item>
    - filterComboBox: ComboBox <String>

    - primaryStage: Stage
    - selectedFile: File

    + addItemButtonClicked(ActionEvent)
    + deleteItemsButtonClicked(ActionEvent)
    + viewFilterComboBox()
    + editDescription()
    + clearListClicked(ActionEvent)
    + refreshButtonClicked(ActionEvent)
    + saveOption()
    + saveAsOptionClicked()
    + openOptionClicked(ActionEvent)
    + initialize()
    + viewCompletedOnlyClicked(ObservableList<Item>): FilteredList<Item>
    + viewUncompletedOnlyButtonClicked(ObservableList<Item>): FilteredList<Item>
    + addItem(CheckBox isComplete, String item, String description, LocalDate dueDate, ToDoList selectedList): ToDoList
    + saveChanges()
    + deleteItems(Item, ObservableList<Item>): ObservableList<Item>
    + setChangedDueDate(LocalDate)
    + setChangedDescription(String)
    + setChangedStatus(CheckBox)
    + setPrimaryStage(Stage)
    + editDueDateView()
    - clearList(ObservableList<Item>)
    - displayItems(FilteredList<Item>)
    - observableListToArrayList(): ArrayList<Item>
    - initTable()
    - editColumns()
    - dateFormatter(String): LocalDate
    - openFile()
    - loadFromPrevious(File)
    - saveFile(ObservableList<Item>, File)
    - makeListSerializable(ObservableList<Item>): ArrayList<SerItem>
    - makeItemSerializable(Item): SerItem
    - makeListDeserializable(List<SerItem>): ObservableList<Item>
    - turnSerItemToItem(SerItem): Item
}

class DueDateViewController{
    - selectedItem: Item
    - dueDateStage: Stage

    - newDueDatePicker: DatePicker
    - itemDescriptionLabel: Label

    + saveChangesButtonClicked(ActionEvent)
    + saveChanges(LocalDate)
    + setDueDateStage(Stage)
    + initData(Item)
}

class SerItem{
    - serDescription: String
    - serDueDate: String
    - serIsCompleted:boolean

    + SerItem(String, String, boolean)
    + getSerDescription(): String
    + getSerDueDate(): String
    + getSerIsCompleted(): boolean
}

class Item{
    - isComplete: CheckBox
    - item: SimpleStringProperty
    - description: SimpleStringProperty
    - dueDate: LocalDate

    + Item(CheckBox, String, String, LocalDate)
    + isComplete(): CheckBox
    + setComplete(CheckBox)
    + getItem(): String
    + itemProperty(): SimpleStringProperty
    + setItem(String)
    + getDescription(): String
    + descriptionProperty(): SimpleStringProperty
    + setDescription(String)
    + getDueDate(): LocalDate
    + setDueDate(LocalDate)
}

javafx.Application <|-- ToDoListApp
ToDoListApp -- ToDoListController
ToDoListController -- Item
DueDateViewController -- Item
ToDoListController -- SerItem
ToDoListController -- DueDateViewController

@enduml